services:
  - type: web
    name: shopify-webhooks-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - '**/*'
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production