services:
  - type: web
    name: shopify-webhook-handler
    env: node
    buildCommand: npm install
    startCommand: node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.15.1
      - key: NPM_CONFIG_PRODUCTION
        value: false
    autoDeploy: true