services:
  - type: web
    name: shopify-webhook-handler
    env: node
    buildCommand: |
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      echo "Installing dependencies..."
      npm ci --include=dev
      echo "Validating build environment..."
      node scripts/validate-build.js
      echo "Running TypeScript compilation..."
      npm run build:production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.15.1
      - key: NPM_CONFIG_PRODUCTION
        value: false
    autoDeploy: true 