services:
  - type: web
    name: shopify-webhook-handler
    env: node
    buildCommand: |
      set -e
      echo "=== Render Build Process Started ==="
      echo "Initial working directory: $(pwd)"
      echo "Home directory: $HOME"
      echo "Render project directory (should be our root): $RENDER_PROJECT_PATH"
      
      # Ensure we're in the project root
      cd $RENDER_PROJECT_PATH || cd /opt/render/project
      echo "Build working directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      
      echo "=== Installing Dependencies ==="
      npm ci --include=dev
      
      echo "=== Verifying TypeScript Configuration ==="
      cat tsconfig.json | grep -A 5 -B 5 '"outDir"'
      
      echo "=== Building Application ==="
      npm run build:production
      
      echo "=== Verifying Build Output ==="
      echo "Current directory after build: $(pwd)"
      echo "Contents of current directory:"
      ls -la
      echo "Checking for dist directory:"
      if [ -d "dist" ]; then
        echo "✅ dist directory found"
        echo "Contents of dist directory:"
        ls -la dist/
        if [ -f "dist/index.js" ]; then
          echo "✅ dist/index.js found"
        else
          echo "❌ dist/index.js missing"
          echo "Files in dist:"
          find dist -name "*.js" -type f || echo "No JS files in dist"
        fi
      else
        echo "❌ dist directory not found"
        echo "Searching for any compiled files:"
        find . -name "index.js" -type f 2>/dev/null || echo "No index.js files found anywhere"
      fi
      echo "=== Build Process Complete ==="
    startCommand: |
      echo "=== Starting Application ==="
      echo "Startup working directory: $(pwd)"
      echo "Checking for main file:"
      if [ -f "dist/index.js" ]; then
        echo "✅ Found dist/index.js, starting application"
        node dist/index.js
      else
        echo "❌ dist/index.js not found"
        echo "Current directory contents:"
        ls -la
        echo "Looking for any index.js files:"
        find . -name "index.js" -type f 2>/dev/null || echo "No index.js files found"
        exit 1
      fi
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.15.1
      - key: NPM_CONFIG_PRODUCTION
        value: false
    autoDeploy: true