services:
  - type: web
    name: shopify-webhook-handler
    env: node
    buildCommand: npm ci --only=production=false && npm run build:production
    startCommand: node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.9.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: BUN_INSTALL
        value: "0"
      - key: DISABLE_BUN
        value: "1"
    autoDeploy: true