services:
  - type: web
    name: shopify-webhook-handler
    env: node
    buildCommand: |
      set -e
      echo "=== Node.js Build Process Started ==="
      node --version
      npm --version
      echo "=== Installing Dependencies ==="
      npm ci --include=dev
      echo "=== Verifying Key Dependencies ==="
      npm list --depth=0 | grep -E "(bullmq|express|typescript)" || echo "Some dependencies missing"
      echo "=== Building Application ==="
      npm run build:production
      echo "=== Verifying Build Output ==="
      ls -la dist/
      test -f dist/index.js || (echo "ERROR: Main build file missing" && exit 1)
      echo "=== Build Process Complete ==="
    startCommand: node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.15.1
      - key: NPM_CONFIG_PRODUCTION
        value: false
    autoDeploy: true