services:
  - type: web
    name: shopify-webhook-handler
    env: node
    buildCommand: |
      echo "Starting build process..."
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      echo "Current directory: $(pwd)"
      echo "Clearing npm cache..."
      npm cache clean --force
      echo "Installing all dependencies (including dev)..."
      npm install
      echo "Verifying bullmq installation..."
      npm list bullmq || echo "bullmq not found in npm list"
      echo "Checking bullmq in node_modules..."
      ls -la node_modules/ | grep bullmq || echo "bullmq not found in node_modules"
      echo "Running TypeScript type check..."
      npm run typecheck
      echo "Running TypeScript compilation..."
      npm run build:production
      echo "Verifying compiled files..."
      ls -la dist/
      echo "Verifying compiled worker exists..."
      ls -la dist/workers/ || echo "workers directory not found"
      echo "Build completed successfully!"
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.9.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
    autoDeploy: true