services:
  - type: web
    name: shopify-webhook-handler
    env: node
    buildCommand: npm ci && npm run build:production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.15.1
    autoDeploy: true 